# Generated by Django 2.2.6 on 2019-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Title',
            field=models.CharField(max_length=10),
        ),
    ]
