# Generated by Django 2.2.6 on 2019-10-01 13:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_auto_20191001_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
        migrations.AlterField(
            model_name='images',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
        migrations.AlterField(
            model_name='images',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
