# Generated by Django 2.2.6 on 2019-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0005_auto_20191001_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='fs'),
        ),
        migrations.AlterField(
            model_name='images',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='fs'),
        ),
        migrations.AlterField(
            model_name='images',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to='fs'),
        ),
    ]
